#!/bin/bash

# Copyright 2024, ASAM e.V.
# This Source Code Form is subject to the terms of the Mozilla
# Public License, v. 2.0. If a copy of the MPL was not distributed
# with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
readonly CONFIG_FILE=$1

source /app/openscenario-venv/bin/activate
cd /app/qc-openscenarioxml
python main.py -c $CONFIG_FILE
cp *.xqar /app/framework/build/bin/
