name: Create Release with Pre-Built Installers

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with "v" (e.g., v1.0.0)

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Ubuntu Artifact
      uses: actions/download-artifact@v3
      with:
        name: qc-framework-executables-ubuntu

    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: qc-framework-executables-windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          qc-framework-executables-ubuntu.zip
          qc-framework-executables-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
