name: Build framework on Linux Docker

on:
  # execute on every PR made targeting the branches bellow
  pull_request:
    branches:
      - main
    paths: # we only include paths critical for building to avoid unnecessary runs
      - src/**
      - include/**
      - scripts/cmake/**
      - test/**
      - .github/workflows/**
      - doc/**
      - qc_framework/**
      - docker/**

  # execute on every push made targeting the branches bellow
  push:
    branches:
      - main
    paths: # we only include paths critical for building to avoid unnecessary runs
      - src/**
      - include/**
      - scripts/cmake/**
      - test/**
      - .github/workflows/**
      - doc/**
      - qc_framework/**
      - docker/**

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -f docker/Dockerfile.linux --target unit_test -t unit_test .
          docker build -f docker/Dockerfile.linux --target framework_test -t framework_test .

      - name: Unit test execution
        if: github.event_name == 'pull_request'
        run: |
          docker run -v ${{ github.workspace }}:/out --name unit_test unit_test

      - name: Archive unit test results
        if: github.event_name == 'pull_request' && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: ${{ github.workspace }}/LastTest.log

      - name: Framework test execution
        if: github.event_name == 'pull_request'
        run: |
          docker run -v ${{ github.workspace }}:/out --rm --name framework_test framework_test

      - name: Archive framework test results
        if: github.event_name == 'pull_request' && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: framework-test-report
          path: |
            ${{ github.workspace }}/runtime_test.log
            ${{ github.workspace }}/qc-output-*/
