name: Create Release with Pre-Built Installers

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with "v" (e.g., v1.0.0)

  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      release_name:
        description: 'Release name'
        required: false
      release_body:
        description: 'Description of the release'
        required: false
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: 'false'

jobs:

  trigger-builds:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Linux Build
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build-on-change-linux-bare.yaml
        token: ${{ secrets.GITHUB_TOKEN }}


  wait-for-builds:
    runs-on: ubuntu-latest
    needs: trigger-builds
    steps:
    - name: Download Ubuntu 20.04 Artifact
      uses: actions/download-artifact@v2
      with:
        name: qc-framework-executables-ubuntu-20.04
        path: |
          ./build/src/result_pooling/ResultPooling
          ./build/src/report_modules/report_module_text/TextReport
          ./build/src/report_modules/report_module_github_ci/GithubCIReport
          ./build/src/report_modules/report_module_gui/ReportGUI

    - name: Download Ubuntu 22.04 Artifact
      uses: actions/download-artifact@v2
      with:
        name: qc-framework-executables-ubuntu-22.04
        path: |
          ./build/src/result_pooling/ResultPooling
          ./build/src/report_modules/report_module_text/TextReport
          ./build/src/report_modules/report_module_github_ci/GithubCIReport
          ./build/src/report_modules/report_module_gui/ReportGUI

  create-release:
    runs-on: ubuntu-latest
    needs: wait-for-builds
    steps:
    - name: Package and create release
      run: |
        # Package the artifacts or prepare them for release
        tar -czvf qc-framework-executables-ubuntu-20.04.tar.gz qc-framework-executables-ubuntu-20.04
        tar -czvf qc-framework-executables-ubuntu-22.04.tar.gz qc-framework-executables-ubuntu-22.04

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Use the tag name that triggered the workflow
        release_name: ${{ github.ref_name }}
        body: "Release for ${{ github.ref_name }}"
        prerelease: false
        files: |
          qc-framework-executables-ubuntu-20.04.tar.gz
          qc-framework-executables-ubuntu-22.04.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
