name: Test runtime on Windows

on:
  # execute on every PR made targeting the branches bellow
  pull_request:
    branches:
      - main
      - develop # can be removed on main merge
    paths: # we only include paths critical for building to avoid unnecessary runs
      - src/**
      - include/**
      - scripts/cmake/**
      - test/**
      - .github/workflows/**
      - doc/**
      - runtime/**
      - docker/**

  # execute on every push made targeting the branches bellow
  push:
    branches:
      - main
      - develop # can be removed on main merge
    paths: # we only include paths critical for building to avoid unnecessary runs
      - src/**
      - include/**
      - scripts/cmake/**
      - test/**
      - .github/workflows/**
      - doc/**
      - runtime/**
      - docker/**

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-windows:
    runs-on: windows-2019
    env:
      WORKING_PATH: "D:\\a"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute pre built TextReport exe
        run: |
          cd D:\\a\qc-framework\\qc-framework\\.github\\workflows\\windows-pre-built\\bin
          dir

          .\TextReport.exe

      - name: Execute pre built ResultPooling exe
        run: |
          cd D:\\a\qc-framework\\qc-framework\\.github\\workflows\\windows-pre-built\\bin

          $process = Start-Process -FilePath ".\ResultPooling.exe" -ArgumentList "--help" -RedirectStandardOutput "output.txt" -Wait -PassThru
          Get-Content "output.txt"

        shell: pwsh

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: D:\\a\qc-framework\\qc-framework\\.github\\workflows\\windows-pre-built\\bin\\output.txt
